# NumPy
https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [1]:
import numpy as np

In [2]:
# 1. create 1d array from 0 to 9
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 2. create boolean 3x3 array with all True
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
# 3. extract all od numbers from the arr created in 1.
arr = np.arange(0,10)
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [13]:
# 4. How to replace items that satisfy a condition with another value in numpy array?
np.where(arr%2!=0,-1,arr)
# arr[arr % 2 == 1] = -1 # this actually replaces the data

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [16]:
# 5. How to replace items that satisfy a condition without affecting the original array?
np.where(arr%2!=0,-1,arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [17]:
# old one
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# 6. How to reshape an array?
arr.reshape(2,-1) # -1 automatically sets the cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
# 8. How to stack two arrays vertically?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
print(a)
print(b)
np.concatenate((a,b),axis=0)
np.vstack((a,b))
np.r_[a,b]

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
# 9. stack horizontally
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [28]:
aa = np.arange(10)
bb = np.repeat(1,10)

In [30]:
np.vstack((aa,bb))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [31]:
np.hstack((aa,bb))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [34]:
# does not work cause both arrays only ave one axis
# np.concatenate((aa,bb),axis=1)

In [36]:
# 10. How to generate custom sequences in numpy without hardcoding?
a = np.array([1,2,3])

In [45]:
np.hstack((a.repeat(3,0),np.tile(a,3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [51]:
# 11. get common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [57]:
# 12.How to remove from one array those items that exist in another?
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)
#[element for element in a if not element in b]

array([1, 2, 3, 4])

In [67]:
# 13. How to get the positions where elements of two arrays match?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

In [75]:
# 14. How to extract all numbers between a given range from a numpy array?
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>5) & (a<=10)]
a[ np.where((a>5) & (a<=10))]
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 6,  9, 10])

In [87]:
# 15. How to make a python function that handles scalars to work on numpy arrays?
def maxx(x, y):
    #return np.max(np.vstack((a,b)), axis=0)
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5

5

In [86]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [83]:
np.max(np.vstack((a,b)), axis=0)

array([6, 7, 9, 8, 9, 7, 5])

In [99]:
pair_max = np.vectorize(maxx, otypes=[float])

In [103]:
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [91]:
oct(123)

'0o173'

In [104]:
#oct([123,345])

In [94]:
oct_array = np.frompyfunc(oct, 1, 1)
oct_array(np.array((10, 30, 100)))

array(['0o12', '0o36', '0o144'], dtype=object)

In [105]:
# 16. How to swap two columns in a 2d numpy array?
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [106]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [111]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [113]:
# 17. How to swap two rows in a 2d numpy array?
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [114]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [125]:
# 18. How to reverse the rows of a 2D array?
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [128]:
arr[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [127]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [130]:
# 19. How to reverse the columns of a 2D array?
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [131]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [134]:
# 20. How to create a 2D array containing random floats between 5 and 10?
np.random.uniform(5,10,size=(5,3))

array([[8.66454469, 9.21664713, 9.06386214],
       [7.47521758, 6.89054549, 6.62895667],
       [5.27345735, 9.51043919, 9.0893089 ],
       [8.25895418, 8.8072234 , 6.80359849],
       [8.27309337, 6.50709382, 5.94919287]])

In [172]:
# 21. How to print only 3 decimal places in python numpy array?
rand_arr = np.random.random((5,3))
def nice_print(x):
    return ("""{:.3f}""".format(x))

In [173]:
nice_print(3.22222)

'3.222'

In [182]:
rand_arr

array([[0.61491743, 0.18034026, 0.90258261],
       [0.56527128, 0.83069367, 0.55030775],
       [0.38592844, 0.35251394, 0.90782899],
       [0.02232816, 0.99221166, 0.30282807],
       [0.79405707, 0.62046031, 0.41026149]])

In [180]:
nice_print_vec = np.vectorize(nice_print, otypes=[float])

In [181]:
nice_print_vec(rand_arr)

array([[0.615, 0.18 , 0.903],
       [0.565, 0.831, 0.55 ],
       [0.386, 0.353, 0.908],
       [0.022, 0.992, 0.303],
       [0.794, 0.62 , 0.41 ]])

In [171]:
float(3.22)

3.22

In [183]:
# 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [3]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.43404942e-04, 2.78369385e-04, 4.24517591e-04],
       [8.44776132e-04, 4.71885619e-06, 1.21569121e-04],
       [6.70749085e-04, 8.25852755e-04, 1.36706590e-04]])

In [6]:
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [7]:
# 23. How to limit the number of items printed in output of numpy array?

In [9]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.set_printoptions(threshold=5)

In [11]:
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [12]:
# 24. How to print the full numpy array without truncating
# set threshold to np.nan